
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;
	
	private global::Gtk.Button buttonPlayPause;
	
	private global::Gtk.Button buttonSettings;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label labelTimeForLongBreak;
	
	private global::Gtk.Label labelTimeForShortBreak;
	
	private global::Gtk.Label labelTimeForWorkout;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Relaxer");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(21));
		// Container child table1.Gtk.Table+TableChild
		this.buttonPlayPause = new global::Gtk.Button ();
		this.buttonPlayPause.CanFocus = true;
		this.buttonPlayPause.Name = "buttonPlayPause";
		this.buttonPlayPause.UseUnderline = true;
		this.buttonPlayPause.Label = global::Mono.Unix.Catalog.GetString ("Pause");
		this.table1.Add (this.buttonPlayPause);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonPlayPause]));
		w1.TopAttach = ((uint)(3));
		w1.BottomAttach = ((uint)(4));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.buttonSettings = new global::Gtk.Button ();
		this.buttonSettings.CanFocus = true;
		this.buttonSettings.Name = "buttonSettings";
		this.buttonSettings.UseUnderline = true;
		this.buttonSettings.Label = global::Mono.Unix.Catalog.GetString ("Settings");
		this.table1.Add (this.buttonSettings);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonSettings]));
		w2.TopAttach = ((uint)(3));
		w2.BottomAttach = ((uint)(4));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Time left to short break: ");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Time left to long break: ");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Time left to workout");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelTimeForLongBreak = new global::Gtk.Label ();
		this.labelTimeForLongBreak.Name = "labelTimeForLongBreak";
		this.labelTimeForLongBreak.LabelProp = global::Mono.Unix.Catalog.GetString ("label5");
		this.table1.Add (this.labelTimeForLongBreak);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelTimeForLongBreak]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelTimeForShortBreak = new global::Gtk.Label ();
		this.labelTimeForShortBreak.Name = "labelTimeForShortBreak";
		this.labelTimeForShortBreak.LabelProp = global::Mono.Unix.Catalog.GetString ("labelTimeForShortBreak");
		this.table1.Add (this.labelTimeForShortBreak);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelTimeForShortBreak]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelTimeForWorkout = new global::Gtk.Label ();
		this.labelTimeForWorkout.Name = "labelTimeForWorkout";
		this.labelTimeForWorkout.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
		this.table1.Add (this.labelTimeForWorkout);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelTimeForWorkout]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.table1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 325;
		this.DefaultHeight = 129;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonSettings.Clicked += new global::System.EventHandler (this.ButtonSettings_Click);
		this.buttonPlayPause.Clicked += new global::System.EventHandler (this.ButtonPlayPause_Click);
	}
}
