
// This file has been generated by the GUI designer. Do not modify.
namespace Relaxer
{
	public partial class RelaxDialog
	{
		private global::Gtk.Label labelText;
		
		private global::Gtk.Button buttonCancel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Relaxer.RelaxDialog
			this.Name = "Relaxer.RelaxDialog";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(2));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			// Internal child Relaxer.RelaxDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.labelText = new global::Gtk.Label ();
			this.labelText.Name = "labelText";
			this.labelText.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.labelText.Wrap = true;
			this.labelText.Justify = ((global::Gtk.Justification)(2));
			w1.Add (this.labelText);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.labelText]));
			w2.Position = 0;
			// Internal child Relaxer.RelaxDialog.ActionArea
			global::Gtk.HButtonBox w3 = this.ActionArea;
			w3.Name = "dialog1_ActionArea";
			w3.Spacing = 10;
			w3.BorderWidth = ((uint)(5));
			w3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-close";
			this.AddActionWidget (this.buttonCancel, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3 [this.buttonCancel]));
			w4.Expand = false;
			w4.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.ButtonClose_Clicked);
		}
	}
}
