
// This file has been generated by the GUI designer. Do not modify.
namespace Relaxer
{
	public partial class SettingsDialog
	{
		private global::Gtk.Table table;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.SpinButton spinLongBreakInterval;
		
		private global::Gtk.SpinButton spinLongBreakTime;
		
		private global::Gtk.SpinButton spinShortBreakInterval;
		
		private global::Gtk.SpinButton spinShortBreakTime;
		
		private global::Gtk.SpinButton spinWorkoutInterval;
		
		private global::Gtk.SpinButton spinWorkoutTime;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Relaxer.SettingsDialog
			this.Name = "Relaxer.SettingsDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Relaxer.SettingsDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.table.Name = "table";
			this.table.RowSpacing = ((uint)(6));
			this.table.ColumnSpacing = ((uint)(6));
			this.table.BorderWidth = ((uint)(15));
			// Container child table.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Interval between short breaks");
			this.table.Add (this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table [this.label1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Interval between long breaks");
			this.table.Add (this.label2);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table [this.label2]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Interval between workouts");
			this.table.Add (this.label3);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table [this.label3]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Short break time");
			this.table.Add (this.label4);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table [this.label4]));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Long break time");
			this.table.Add (this.label5);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table [this.label5]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Workout time");
			this.table.Add (this.label6);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table [this.label6]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.spinLongBreakInterval = new global::Gtk.SpinButton (0, 10000, 1);
			this.spinLongBreakInterval.CanFocus = true;
			this.spinLongBreakInterval.Name = "spinLongBreakInterval";
			this.spinLongBreakInterval.Adjustment.PageIncrement = 10;
			this.spinLongBreakInterval.ClimbRate = 1;
			this.spinLongBreakInterval.Numeric = true;
			this.table.Add (this.spinLongBreakInterval);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table [this.spinLongBreakInterval]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.spinLongBreakTime = new global::Gtk.SpinButton (0, 10000, 1);
			this.spinLongBreakTime.CanFocus = true;
			this.spinLongBreakTime.Name = "spinLongBreakTime";
			this.spinLongBreakTime.Adjustment.PageIncrement = 10;
			this.spinLongBreakTime.ClimbRate = 1;
			this.spinLongBreakTime.Numeric = true;
			this.table.Add (this.spinLongBreakTime);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table [this.spinLongBreakTime]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(3));
			w9.RightAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.spinShortBreakInterval = new global::Gtk.SpinButton (0, 10000, 1);
			this.spinShortBreakInterval.CanFocus = true;
			this.spinShortBreakInterval.Name = "spinShortBreakInterval";
			this.spinShortBreakInterval.Adjustment.PageIncrement = 10;
			this.spinShortBreakInterval.ClimbRate = 1;
			this.spinShortBreakInterval.Numeric = true;
			this.table.Add (this.spinShortBreakInterval);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table [this.spinShortBreakInterval]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.spinShortBreakTime = new global::Gtk.SpinButton (0, 10000, 1);
			this.spinShortBreakTime.CanFocus = true;
			this.spinShortBreakTime.Name = "spinShortBreakTime";
			this.spinShortBreakTime.Adjustment.PageIncrement = 10;
			this.spinShortBreakTime.ClimbRate = 1;
			this.spinShortBreakTime.Numeric = true;
			this.table.Add (this.spinShortBreakTime);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table [this.spinShortBreakTime]));
			w11.LeftAttach = ((uint)(3));
			w11.RightAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.spinWorkoutInterval = new global::Gtk.SpinButton (0, 10000, 1);
			this.spinWorkoutInterval.CanFocus = true;
			this.spinWorkoutInterval.Name = "spinWorkoutInterval";
			this.spinWorkoutInterval.Adjustment.PageIncrement = 10;
			this.spinWorkoutInterval.ClimbRate = 1;
			this.spinWorkoutInterval.Numeric = true;
			this.table.Add (this.spinWorkoutInterval);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table [this.spinWorkoutInterval]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table.Gtk.Table+TableChild
			this.spinWorkoutTime = new global::Gtk.SpinButton (0, 10000, 1);
			this.spinWorkoutTime.CanFocus = true;
			this.spinWorkoutTime.Name = "spinWorkoutTime";
			this.spinWorkoutTime.Adjustment.PageIncrement = 10;
			this.spinWorkoutTime.ClimbRate = 1;
			this.spinWorkoutTime.Numeric = true;
			this.table.Add (this.spinWorkoutTime);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table [this.spinWorkoutTime]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1 [this.table]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Internal child Relaxer.SettingsDialog.ActionArea
			global::Gtk.HButtonBox w15 = this.ActionArea;
			w15.Name = "dialog1_ActionArea";
			w15.Spacing = 10;
			w15.BorderWidth = ((uint)(5));
			w15.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15 [this.buttonCancel]));
			w16.Expand = false;
			w16.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w15 [this.buttonOk]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 450;
			this.DefaultHeight = 158;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.ButtonCancel_Click);
			this.buttonOk.Clicked += new global::System.EventHandler (this.ButtonOk_Click);
		}
	}
}
